/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_julia_svd */

#ifndef _Included_java_julia_svd
#define _Included_java_julia_svd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_julia_svd
 * Method:    get_svd
 * Signature: ([DII)Lsvd_results;
 */
JNIEXPORT jobject JNICALL Java_java_1julia_1svd_get_1svd
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     java_julia_svd
 * Method:    get_singularvals
 * Signature: ([DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_java_1julia_1svd_get_1singularvals
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
